[workspace]

members = [
    "non_stdin",
    "type_conversion",
    "three_and_a_bit",
    "byte_sized",
    "byte_sized_wrap",
    "string_length",
    "reboot_universe",
    "there_and_back",
    "zero_to_ten",
    "x_marks_spot",
    "boxes",
    "amnesia"
]
